.travis.yml
Forgot to mention that I also enabled [Travis-CI](https://travis-ci.org) and [Coveralls](https://coveralls.io) via the `.travis.yml` file but you have to turn them on in your repo.
If you're not familiar Travis is a continuous integration service that is free for public repos and is a really easy way to run the test suite in a clean environment against multiple versions of Python and Coveralls keeps track of the code coverage report generated by `nosetests --with-coverage`.  Both also have badges that can be added to the readme.  They both generate reports automatically for pull requests, which is really useful.
This pull request adds `PyPy3` to the Travis configfile, which I neglected to include originally.  You can see what the Travis and Coveralls report looks like for my branch before …
=> Added PyPy3 to Travis-CI

LICENSE.txt, README.rst, emoji/__init__.py, emoji/core.py, emoji/unicode_codes.py, tests/test_core.py, tests/test_unicode_codes.py
@carpedm20 Adding aliases and defaulting to `is_alias=True` broke existing functionality and only gives users access to the alias set.
Rather than changing the default to `is_alias=False` I included the default emoji set in the alias set by adding the default emoji set to the aliases variable first and adding the  aliases second so everything is overwritten properly.
=> Fixed broken alias handling.

setup.py
Closes #2
Closes #5
Installs were choking on the non-ascii characters in the readme.
=> Use codecs.open() instead of open() when processing readme in setup.py

utils/get-codes-from-unicode-consortium.py
Without this change, BeautifulSoup4 gives this warning when running the `utils/get-codes-from-unicode-consortium.py` script:
```
$ python ./utils/get-codes-from-unicode-consortium.py
/Users/adam/code/emoji/venv/lib/python3.4/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
To get rid of this warning, change this:
BeautifulSoup([your markup])
to this:
BeautifulSoup([your markup], "html.parser")
markup_type=markup_type))
```
=> Fix BeautifulSoup warning

example/example.py
at runtime expect to see NO ICON - clarify - at runtime expect to see TEXT instead. 
Without this hint, the example is pretty much worthless for demonstration purposes.
=> at runtime expect to see NO ICON - clarify

README.rst
Adding this so it's not necessary to look into the code to see how to do this. :)
There also seems to have been an error in the previous documentation. `emoji.emojize('Python is :thumbs_up_sign:')` doesn't seem to work, the "standard" emoji code seems to be `:thumbs_up:`. That's also what `demojize` returns.
=> add demojize to README

emoji/__init__.py, emoji/core.py
Fix origin methods emoji_lis and emoji_count.
The original function imported the wrong module name and would raise the below Error.
`` ImportError: No module named 'emoji'``.
This pull request modify the import module in core.py and add the new methods in __init__.py.
=> Bug Fixed - emoji_lis and emoji_count

emoji/core.py
Added the optional use_alias argument to align with the parameters of the emojize() function.
For our application, we want to convert text with unicode emojis into Slack style (colon bounded) text, and we want the text labels from the UNICODE_EMOJI_ALIAS dict.
=> Allow optional use_aliases argument in demojize.

emoji/unicode_codes.py
GitHub only understands `:robot:`, and does not have `:robot_face:` in its emoji list.
I've attempted to put the alias in an appropriate spot in the list of aliases—though I admit, I could not figure out exactly how the list is sorted. Apologies if it's in the wrong spot.
=> Add `:robot:` as alias for `:robot_face:` emoji

emoji/unicode_codes.py
Good evening. When using the flag `use_aliases=True`, `:egg:` displays scrambled eggs in the pan, it seems this is not unexpected behavior, but that would not break the dependencies added egg like `:egg2:`
=> #107 - Fix: :egg: error aliace or should it be

utils/get-codes-from-unicode-consortium.py
Warning message:
```
./utils/get-codes-from-unicode-consortium.py:43: SyntaxWarning: "is" with a literal. Did you mean "=="?
if len(c) is 6:
```
Fixes #115
=> Fix SyntaxWarning using a literal with 'is' in Python 3.8

emoji/__init__.py
Some tools require `__all__` variable to recognise that the name is being re-exported.
=> Add `__all__` to `emoji/__init__.py`

emoji/core.py, tests/test_core.py
Fixes #117 #77
emoji_lis, emoji_count were not prioritizing multi-character emojis. Therefore, a string like `Hello 🇫🇷`was counted as 2 emojis instead of one.
My PR uses the regexp to fix this issue. I have added tests
=> Handle multi-character emojis in emoji_lis, emoji_count

emoji/core.py, tests/test_core.py
This library had a `distinct_emoji_lis` function to distinct list of emojis from the string, but it didn't work correctly due to an implementation error.
It has been fixed, please review it.
=> Fixed implementation error of `emoji.distinct_emoji_lis`

README.rst, emoji/__init__.py, emoji/core.py, tests/test_core.py
This adds `replace_emoji` to the top-level module, so users can use it by just importing emoji. For example
```py
import emoji
emoji.replace_emoji("original string", "x")
```
I also made the following tweaks:
- Changed the param order, such that the replacement char is the 2nd argument of `replace_emoji`. This seems like something users would override more often than `language` (but maybe this is because I'm a native english speaker and I like the default language choice :wink: )
- Added tests
- Changed instructions for running unit tests to use `pytest` instead of `nosetests`
=> Add replace_emoji to top-level module

.github/workflows/updateGithubPages.yml, utils/gh-pages/.gitignore, utils/gh-pages/README.rst, utils/gh-pages/generatePages.py, utils/gh-pages/main.css, utils/gh-pages/main.js, utils/gh-pages/requirements.txt, utils/gh-pages/template.html
This can generate a website that contains all table of all emoji that are currently supported by the package. The website can be deployed to github pages.
See here: https://cvzi.github.io/emoji/
It should look like this:
To generate the html files (index.html and all.html) run:
```bash
pip install -r utils/gh-pages/requirements.txt
python utils/gh-pages/generatePages.py
```
The github action (in [updateGithubPages.yml](https://github.com/cvzi/emoji/blob/master/.github/workflows/updateGithubPages.yml)) will automatically update the HTML after every release and push the changes to the branch 'gh-pages' (this is the default place for the Github Pages). This action can also be run manually in the actions tab of the repository.
=> Add overview of all emoji on Github Pages

emoji/core.py
Some of the characters used in the French emoji names are currently not included in the regular expression for matching emoji names. One example is œ.
As word characters aren't continuous in Unicode it is impossible to correctly match them via a range expression. Thus, I converted the existing range to the word characters group which should be future proof regarding additional languages and avoids accidentally including non-word characters that could have been included by an overly vast range.
=> Fix some of the French emoji names not being matched

CHANGES.md, emoji/core.py
The fix in  PR #178 was sadly incomplete as it only worked on Python 3 but not on Python 2.
=> Fix matching of non-ASCII emoji names on Python 2

CHANGES.md, emoji/__init__.py, emoji/core.py, tests/test_core.py, tests/test_dict.py
This pull request improves the `demojize` performance. I have replace the big regular expression with a search tree. The method `_get_search_tree()` creates the tree once on first use. I have put an example of a tree in the comment of `_get_search_tree()`
The `get_emoji_regexp()` still exists but it is unused now. 
Performance is faster on my machine for both single emoji and a long text. This is approximately how much faster it is on my machine:
| Python             | 2.7  | 3.6  | 3.10  |  |
|--------------------|-------|------|-------|-------|
| Single emoji:      |   7x  |  7x  |  12x  | faster |
| Text [200k chars]: | 1.5x  |  7x  |  23x  | faster |
----
I have also added `emojize(language='alias')` as an alternative to `emojize(use_aliases=True)`.
When someone uses …
=> Demojize performance

README.rst, emoji/__init__.py, emoji/core.py, utils/gh-pages/generatePages.py, utils/gh-pages/requirements.txt, utils/gh-pages/template.html
*  Replace `use_aliases=True` with `language='alias'` in README and Github pages
*  I somehow broke the github pages, because currently the page starts with no language selected. Now the `'en'` checkbox will be selected by default. https://carpedm20.github.io/emoji/ vs https://cvzi.github.io/emoji/
=> Readme and github pages

.github/workflows/updateGithubPages.yml
This should prevent the crash `rm: cannot remove 'docs': No such file or directory`
#210
=> Fix github action

CHANGES.md, README.rst, docs/README.md, docs/api.rst, docs/conf.py, docs/index.rst, docs/install.rst, emoji/core.py, setup.py, utils/get_codes_from_unicode_emoji_data_files.py, utils/gh-pages/README.rst, utils/gh-pages/template.html
* Add Trove classifiers for Python 3.10 and 3.11
* Add `python_requires` to help pip
* Fix some typos: Unicode, PyPI and GitHub
=> Add Trove classifiers for Python 3.10 and 3.11

setup.py
#166 forgot to add the `py.typed` marker to the package.
=> Added missed `py.typed` `package_data`

.github/workflows/pythonTests.yml
Python 3.11.1 is out, let's just say `3.11` to test the latest.
And we can also now test `3.12-dev`.
---
And maybe it's time to drop EOL Python 2.7, 3.5 and 3.6?
It would allow modernising the code to use newer features, and reduce the resources used by the CI.
| cycle |  release   | latest | latest release |    eol     |
|:------|:----------:|:-------|:--------------:|:----------:|
| 3.11  | 2022-10-24 | 3.11.1 |   2022-12-06   | 2027-10-24 |
| 3.10  | 2021-10-04 | 3.10.9 |   2022-12-06   | 2026-10-04 |
| 3.9   | 2020-10-05 | 3.9.16 |   2022-12-06   | 2025-10-05 |
| 3.8   | 2019-10-14 | 3.8.16 |   2022-12-06   | 2024-10-14 |
| 3.7   | 2018-06-26 | 3.7.16 |   2022-12-06   | 2023-06-27 |
| 3.6   | 2016-12-22 | 3.6.15 |   2021-09-03   | 2021-12-23 |
| 3.5   | 2015-09-12 | 3.5.10 | …
=> Test 3.11 final and 3.12-dev

.github/workflows/pythonTests.yml, .github/workflows/updateGithubPages.yml, README.rst, docs/README.md, docs/install.rst, utils/README.md, utils/gh-pages/README.rst
Don't invoke `setup.py` directly, it's deprecated.
Short version: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary
Long version: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
---
And use `python -m pip` instead of plain `pip`. You already had this in three places in `updateGithubPages.yml`, let's do it in the others too.
Why: https://snarky.ca/why-you-should-use-python-m-pip/
=> Don't invoke setup.py directly

setup.cfg, setup.py
Building a release:
```bash
python -m pip install --upgrade build
python -m build
``` 
Outputs wheel file to: `dist/emoji-2.2.0-py2.py3-none-any.whl`
Ref:
Fixes #247
Fixes #250 
#226
Notes:
In the future setup.py and setup.cfg can/should be replaced by a single file [pyproject.toml](https://peps.python.org/pep-0621/#example). We can do this if we decide to stop support for Python 2.7
=> Wheel for Python 2 and 3

.github/workflows/pypipublish.yml, pyproject.toml
@TahirJalilov This needs some configuration on Github and Pypi:
Create a new Environment called `pypi` (maybe this needs to be done by @carpedm20 ?):
Goto https://github.com/carpedm20/emoji/settings/environments
Click **New environment** and name it `pypi`
Goto the "Manage"-page of the project, and select **Publishing** on the left side. 
Then fill out the form with:
```
carpedm20
emoji
pypipublish.yml
pypi
```
---
Documentation on this pypi.org-feature:
https://docs.pypi.org/trusted-publishers/adding-a-publisher/
Ref #254
=> Publish to pypi.org automatically on release

emoji/unicode_codes/data_dict.py
This alias is used in the YouTube frontend and the linked emoji site in the repo
=> Add alias for smiling face with heart eyes

.github/workflows/pythonTests.yml, pyproject.toml, tests/test_analyze.py, tests/test_core.py, tests/test_dict.py, tests/test_nfkc.py, tests/test_unicode_codes.py, tests/test_versions.py, tests/test_zwj_common.py, tests/test_zwj_keep.py, tests/test_zwj_remove.py
This fixes a minor problem in the test cases. With pytest the test cases are always executed in the same order. When tests were run manually in a different order, some tests could fail, because the `emoji.config.*` values were changed (or not changed) by previous tests. This PR should make the test cases independent of execution order.
=> Fix tests relying on a fixed execution order

CHANGES.md, MANIFEST.in, emoji/__init__.py, pyproject.toml
This is ready for release now.
Changes:
* Remove dev-dependency `coveralls`, we don't use that
* Add `utils/testutils.py` to MANIFEST.in to include it in source tarballs
=> Prepare for v2.12.0

CHANGES.md, emoji/__init__.py, pyproject.toml
Specify `typing-extensions >= 4.7.0` in pyproject.toml
Fix #297
=> Release 2.12.1

CHANGES.md, MANIFEST.in, emoji/__init__.py, emoji/unicode_codes/__init__.py
read JSON files in binary mode with `open(..., 'rb')`
Fixes #305
=> Fix UnicodeDecodeError v2.13.1

CHANGES.md, emoji/core.py, pyproject.toml, tests/test_core.py, utils/testutils.py
@TahirJalilov You can merge this and afterwards publish release v2.13.1
=> Remove `typing_extensions` dependency on Python 3.9 and higher

emoji/unicode_codes/__init__.py
This PR changes `_loaded_keys` from a `List` to a `Set` in `emoji/unicode_codes/__init__.py`. Using a `Set` drops lookup time from O(N) to O(1), making it faster to check membership. We don’t have tons of elements here, so the speed boost isn’t massive, but it’s still a cleaner, more efficient choice. Simple change.
=> Use set for `_loaded_keys` instead of list
